backend:
  name: git-gateway

media_folder: "public/images"
public_folder: "/public/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Slug", name: "slug", widget: "hidden", default: "{{slug}}" }
